#!/bin/bash
echo "Run these commands to set CORS on your bucket:"
echo ""
echo "1. First, authenticate with Google Cloud:"
echo "   gcloud auth login"
echo ""
echo "2. Then apply CORS configuration:"
echo "   gsutil cors set gcs-cors-config.json gs://aescuvest-uploads-2025"
echo ""
echo "3. Verify CORS was applied:"
echo "   gsutil cors get gs://aescuvest-uploads-2025"
