#!/bin/bash

# IMMEDIATE FIX for 413 errors in production
echo "🚨 EMERGENCY FIX FOR 413 ERRORS"
echo "================================"
echo ""
echo "Run these commands to fix the 413 error immediately:"
echo ""
echo "1. First, update your Cloud Run service with increased limits:"
echo ""
echo "gcloud run services update aescuvest-platform \\"
echo "  --region us-central1 \\"
echo "  --memory 4Gi \\"
echo "  --cpu 2 \\"
echo "  --timeout 3600 \\"
echo "  --max-instances 100"
echo ""
echo "2. Then apply the critical annotation for 1GB uploads:"
echo ""
echo "gcloud run services update aescuvest-platform \\"
echo "  --region us-central1 \\"
echo "  --update-annotations run.googleapis.com/request-timeout=3600s"
echo ""
echo "3. Finally, update the ingress settings:"
echo ""
echo "gcloud run deploy aescuvest-platform \\"
echo "  --region us-central1 \\"
echo "  --source . \\"
echo "  --allow-unauthenticated \\"
echo "  --memory 4Gi \\"
echo "  --cpu 2 \\"
echo "  --timeout 3600 \\"
echo "  --set-env-vars NODE_ENV=production \\"
echo "  --service-account=YOUR_SERVICE_ACCOUNT_EMAIL"
echo ""
echo "IMPORTANT: Cloud Run has a HARD LIMIT of 32MB for HTTP requests."
echo "For files larger than 32MB, you MUST use chunked uploads."
